name: Helm CI
on:
  pull_request:
    paths:
      - "charts/**"
jobs:
  lint-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint chart
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: .ct.yaml
      - name: Create k3s cluster
        uses: jupyterhub/action-k3s-helm@v1
        with:
          k3s-channel: v1.19
          traefik-enabled: false
          metrics-enabled: false
        if: steps.lint.outputs.changed == 'true'
      - name: Install chart
        uses: helm/chart-testing-action@v1.0.0
        if: steps.lint.outputs.changed == 'true'
        with:
          command: install
          config: .ct.yaml

      # GitHub Action reference: https://github.com/jupyterhub/action-k8s-await-workloads
      - name: Await chart readiness
        uses: jupyterhub/action-k8s-await-workloads@v1
        if: steps.lint.outputs.changed == 'true'
        with:
          workloads: "" # all
          namespace: "" # default
          timeout: 150
          max-restarts: 0

      # GitHub Action reference: https://github.com/jupyterhub/action-k8s-namespace-report
      - name: Emit namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: steps.lint.outputs.changed == 'true'
        with:
          namespace: "" # default
          important-workloads: "" # always show logs of these workloads
